export function getAppElements() {
    return {
        body: document.body,
        time: document.querySelector('.pixel-time'),
        date: document.querySelector('.pixel-date'),
        clockTicker: document.querySelector('.clock-marquee'),
        clockTickerTexts: document.querySelectorAll('.clock-marquee-text'),
        weatherSummary: document.getElementById('weather-summary'),
        weatherMeta: document.getElementById('weather-meta'),
        weatherRefreshButton: document.querySelector('.weather-refresh-btn'),
        focusInput: document.getElementById('focus-input'),
        musicForm: document.querySelector('.music-form'),
        musicLoadButton: document.querySelector('.music-load-btn'),
        musicUrlInput: document.getElementById('music-url-input'),
        musicTitle: document.querySelector('.music-title'),
        musicThumbnail: document.querySelector('.music-thumbnail'),
        musicCurrentMeta: document.querySelector('.music-current-meta'),
        musicStatus: document.querySelector('.music-status'),
        musicLoopButton: document.getElementById('music-loop-button'),
        musicVolumeInput: document.getElementById('music-volume-input'),
        musicVolumeValue: document.querySelector('.music-volume-value'),
        musicSeekInput: document.getElementById('music-seek-input'),
        musicCurrentTime: document.querySelector('.music-current-time'),
        musicDuration: document.querySelector('.music-duration'),
        musicLibraryCount: document.querySelector('.music-library-count'),
        musicLibraryList: document.querySelector('.music-library-list'),
        musicLibraryEmpty: document.querySelector('.music-library-empty'),
        musicActions: document.querySelectorAll('[data-music-action]'),
        youtubePlayerHost: document.getElementById('youtube-player')
    };
}
